apiVersion: skaffold/v2beta21
kind: Config
metadata:
   name: backend

build:
   artifacts:
   - image: chukmunnlee/bgg-backend
     context: .
     docker:
        dockerfile: ./Dockerfile
        buildArgs:
           TAG: "16"
           APP_DIR: /app
   local:
      push: false
   tagPolicy:
      envTemplate:
         template: "{{ .IMAGE_VERSION }}"
