---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  labels:
    name: bggapp-deploy
    app: bggapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bggapp-pod
      app: bggapp
  template:
    metadata:
      name: bggapp-pod
      labels:
        name: bggapp-pod
        app: bggapp
    spec:
      containers:
      - name: bgg-backend
        image: chukmunnlee/bgg-backend:v3
        imagePullPolicy: IfNotPresent
        env:
        - name: BGG_DB_HOST
          value: bggdb-svc.bggns.svc.cluster.local
        - name: BGG_NAME
          valueFrom:
             fieldRef:
                fieldPath: metadata.name
        envFrom:
        - configMapRef:
           name: bgg-cm
        - secretRef:
           name: bgg-secret
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  labels:
    name: bggapp-svc
    app: bggapp
spec:
  type: ClusterIP
  selector:
    app: bggapp-pod
    app: bggapp
  ports:
  - name: web
    port: 3000
    protocol: TCP
    targetPort: 3000
