---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bggconfig
  labels:
     app: bgg
data:
  BGG_DB_USER: root
  BGG_VERSION: v1
  EXPORTER: exporter

---
apiVersion: v1
kind: Secret
metadata:
  name: bggconfig
  labels:
     app: bgg
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=
  EXPORTER_PASSWORD: ZXhwb3J0ZXI=
