---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb
  labels:
    app: bggdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bggdb
  template:
    metadata:
      labels:
        app: bggdb
    spec:
      containers:
      - name: bgg-database
        image: chukmunnlee/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
      - name: mysqld-exporter
        image: prom/mysqld-exporter:v0.13.0
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: bggconfig
        - secretRef:
            name: bggsecret
        env:
        - name: DATA_SOURCE_NAME
          value: "$(EXPORTER):$(EXPORTER_PASSWORD)@(localhost:3306)"
        ports:
        - containerPort: 9104
---
apiVersion: v1
kind: Service
metadata:
  name: bggdb
  labels:
    app: bggdb
spec:
  type: ClusterIP
  selector:
    app: bggdb
  ports:
  - name: 3306-3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: web
    port: 9104
    protocol: TCP
    targetPort: 9104
