apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./bggdb.yaml
- ./bggapp.yaml

namespace: bggns
namePrefix: dev-

images:
- name: chukmunnlee/bgg-backend
  newTag: v3
- name: chukmunnlee/bgg-database
  newTag: v3

generatorOptions:
   labels:
      app: bgg

configMapGenerator:
- name: bgg-cm
  literals:
  - BGG_DB_USER=root
  - BGG_VERSION=v3
  - EXPORTER=exporter

secretGenerator:
- name: bgg-secret
  type: Opaque
  literals:
  - BGG_DB_PASSWORD=changeit
  - EXPORTER_PASSWORD=exporter

patchesStrategicMerge:
- |
   apiVersion: apps/v1
   kind: Deployment
   metadata:
      name: bggdb-deploy
   spec:
      template:
         spec:
            containers:
            - name: bgg-database
              imagePullPolicy: Always
- |
   apiVersion: apps/v1
   kind: Deployment
   metadata:
      name: bggapp-deploy
   spec:
      template:
         spec:
            containers:
            - name: bgg-backend
              imagePullPolicy: Always

replacements:
- source: 
   kind: Service
   name: bggdb-svc
  targets:
  - select: 
      kind: Deployment
      name: bggapp-deploy
    fieldPaths:
    - spec.template.spec.containers.[name=bgg-backend].env.[name=BGG_DB_HOST].value
      
